name: Release News Workflow

on:
  # Allow manually starting the workflow incase we need human intervention.
  workflow_dispatch:

  # Runs at 08:17 UTC / 00:17 PST / 01:17 PDT
  # 17 is an arbitrarily chosen to avoid running the workflow during the peak at the beginning of the hour
  schedule:
    - cron: ${{ secrets.CRON }}

permissions: write-all

jobs:
  generate_news_items:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate News Posts
        id: generate_news
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$(date)" >> _posts/date.txt
          ./_scripts/release-notes.sh

      - name: Commit and Push Changes
        if: ${{ steps.generate_news.outputs.changes > 0 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "github-actions-patch-1"
          git commit -m "${{ steps.generate_news.outputs.generated_commit_message }}"
          git push --set-upstream origin github-actions-patch-1
          gh pr create --fill --label release-news --base main
          gh workflow run auto-approve-release-news.yml

