# This is a basic workflow that is manually triggered

name: Release notes workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
permissions: write-all
jobs:
  create_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repo
        uses: actions/checkout@v2
      - name: Create Release Post PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./_scripts/release-notes.sh
